name: Compile sgminer for macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CFLAGS: "-O2 -Wall -arch x86_64"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install osxcross dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar file
        sudo apt-get install -y clang lld

    - name: Download and extract osxcross
      run: |
        wget https://github.com/tpoechtrager/osxcross/releases/download/v0.15.0/apple-darwin19-cross.tar.gz
        tar xf apple-darwin19-cross.tar.gz
        mv osxcross ~/

    - name: Build sgminer
      run: |
        export PATH="$PATH:$HOME/osxcross/target/bin"
        autoreconf -i
        CFLAGS=$CFLAGS ./configure --host=x86_64-apple-darwin19
        make
