name: Compile sgminer for macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CFLAGS: "-O2 -Wall -arch x86_64"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y binutils-apple-darwin
        sudo apt-get install -y g++-apple-darwin

    - name: Build sgminer
      run: |
        autoreconf -i
        CFLAGS=$CFLAGS ./configure
        make
