name: Compile sgminer for macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CFLAGS: "-O2 -Wall -arch x86_64"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone osxcross repository
      run: |
        git clone https://github.com/tpoechtrager/osxcross.git

    - name: Build osxcross toolchain
      run: |
        cd osxcross
        UNATTENDED=yes OSX_VERSION_MIN=10.7 ./build.sh

    - name: Export PATH
      run: |
        echo 'export PATH=$PATH:$PWD/target/bin' >> $GITHUB_ENV

    - name: Build sgminer
      run: |
        cd ../sgminer
        autoreconf -i
        CFLAGS=$CFLAGS ./configure
        make
