name: Compile sgminer

on:
  push:
    branches:
      - main

env:
  CFLAGS: "-O2 -Wall"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        arch: [x86_64, i386]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install -y binutils-apple-darwin
          sudo apt-get install -y g++-apple-darwin
        fi

    - name: Build sgminer
      run: |
        autoreconf -i
        CFLAGS="$CFLAGS -arch ${{ matrix.arch }}" ./configure
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: sgminer-${{ matrix.os }}-${{ matrix.arch }}
        path: sgminer
